pizzas/urls.py
# Defines URL patterns for the Pizzas app. 

# Import the path function in order to map URLs to views. 
from django.urls import path

# Import the views module from the same directory as the current urls.py file. 
from . import views

# This variable helps Django distinguish this urls.py file from the files of the same name in other apps within the project. 
app_name = 'pizzas'

# This variable is a list of individual pages that can be requested from the pizzas app. 
urlpatterns = [
    # First argument is a string that helps django route to the current request properly. 
    # Second argument specifies which function to call in views.py. 
    # Third argument provides the name for the url pattern so we can refer to it in other code sections.  
    # Home page
    path('', views.index, name='index'),
    # Page that shows all pizzas.
    # Adds pizzas into the string argument used for the home page url. 
    path('pizzas/', views.pizzas, name='pizzas'),
    # Detail page for a single pizza.
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    # Page for adding a comment on a pizza page.
    path('comment/<int:pizza_id>/',views.comment,name='comment'),
]

# The second phase consists of defining a path for the form's url. The third phase takes place in views.py.

pizzeria/urls.py
# First two lines import a module and a function to manage URLs for the admin site. 
from django.contrib import admin
from django.urls import path, include

# Defines the urlpatterns variable. 
urlpatterns = [

    # Includes the modules which define all the URLs that can be requested from the admin site. 
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

# Create your models here. A model encapsulates information about an entity and models it, then stores it in the database. 
class Pizza(models.Model):
    # A pizza option for the pizzeria.

    # Use CharField for storing a small amount of text.
    text = models.CharField(max_length=200)

    # Tells Django to automatically set this attribute to the current date and time when a user creates a new pizza.
    date_added = models.DateTimeField(auto_now_add=True)

    # Method to return the string stored in the text attribute. 
    def __str__(self):
        # Return a string representation of the model.
        return self.text

class Topping(models.Model):
    # Toppings for the pizza options listed. 

    # The first attribute, Pizza, is a Foregin Key reference, which references another record in the database, connecting each topping to a specific pizza. 
    # The on-delete argument tells Django that when a pizza is deleted, all toppings associated with that pizza. 
    pizza = models.ForeignKey(Pizza,on_delete=models.CASCADE)

    # Attribute defines an instance of TextField, which doesn't require a size limit. 
    text = models.TextField()

    # This attribute allows to present toppings in the order they were created to place a timestamp next to each topping. 
    date_added = models.DateTimeField(auto_now_add=True) 

    # This class holds extra information for managing a model. For this one, it sets a special attribute telling Django to use 'toppings' to refer to more than one topping.
    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        # Return a string representation of the model of only the first 50 characters of a text.
        return f"{self.text[:50]}..."

# Once you are finished defining your model, migrate the model using the following terminial commands:
    # In an active venv, type: python manage.py makemigrations app_name (pizzas)
    # Next, type python manage.py migrate.
    # Lastly, don't forget to register the model with the admin site in admin.py.

pizzas/forms.py
# Forms correspond to a set of fields which are presented to the end user to enter some data in. 
from django import forms

# Import the topping model which is associated to where users will make comments. 
from .models import Topping

class CommentForm(forms.ModelForm):
    # This class will list the model it is based on and the field to include in the form. 
    class Meta:

        # Build the comment form from the Topping model.
        model = Topping

        # Include only the text field.
        fields = ['text']

        # Gives the 'text' field a blank label.
        labels = {'text':''}

        # The widget attribute overrides Django's default widget(html from element) choices.
        # This attribute customizes the input for the 'text' field so the area will be 80 columns wide instead of 40.
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

# The second phase for displaying the form takes place in the urls.py file.

pizzas/views.py
# Render function returns a requested page. Redirect function sends another request to the given url.
from django.shortcuts import render, redirect

# Import the model associated with the data it needs.
from .models import Pizza

# Import the form associated with the comment insertion form. 
from .forms import CommentForm

# Create your views here. View functions take in information from a request, prepares the data needed to generate a page, and then sends the data back to the browser.
def index(request):
    # The home page for the pizzas app. 
    return render(request, 'pizzas/index.html')

def pizzas(request):
    # Shows all pizzas.

    # Queries the database by asking for the Pizza objects, sorted by the date_added attribute, storing the resulting queryset in pizzas. 
    pizzas = Pizza.objects.order_by('date_added')

    # This is a dictionary in which the keys are names we'll use in the template to access the data, and the values are the data we need to 
    # send to the template.
    context = {'pizzas':pizzas}

    # To build a page that uses data, pass the context variable to render, as well as the request object and the path to the template. 
    return render(request, 'pizzas/pizzas.html', context)

# GET requests are for pages that only read data from the server.
# POST requests are used when the user needs to submit information through a form. 

def pizza(request,pizza_id):
    # Show a single pizza and all its toppings.

    # Use get() to retrieve the pizza, just like in the Django shell. 
    pizza = Pizza.objects.get(id=pizza_id)

    # Gets the toppings associated with this pizza, and orders it according to date_added.
    toppings = pizza.topping_set.order_by('date_added')

    # Stores the pizza and toppings in the context dictionary.
    context = {'pizza':pizza, 'toppings':toppings}

    # Sends the context to the template pizza.html.
    return render(request,'pizzas/pizza.html', context)

def comment(request,pizza_id):
    # Add a comment for the pizza page.

    # Attribute uses the pizza_id to get the correct pizza.
    pizza = Pizza.objects.get(id=pizza_id)

    # Checks whether the request method is POST or GET. 
    # The if block executes if it's a GET request and creates an instance of CommentForm. 
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CommentForm()

    else:
        # POST data submitted; process data. 
        form = CommentForm(data=request.POST)

        if form.is_valid():
            # This attribute tells django to create a comment object and assign it to comment without saving it to the database. 
            comment = form.save(commit=False)
            # Set the pizza attribute of comment to the pizza we pulled from the database at the beginning of the function. 
            comment.pizza = pizza
            comment.save()

            # This renders the pizza page the user made comments on, and they should see their comment on the pizza page.
            return redirect('pizzas:pizza',pizza_id=pizza_id)

    # Display a blank or invalid form. 
    context = {'pizza':pizza,'form':form}
    return render(request,'pizzas/comment.html',context)

# The third phase consists of creating a view function for the form. The fourth phase requires you to create an html file in the templates.

pizzas/templates/pizzas/base.html
<!-- Templates define what the page should look like  -->

<!-- The base.html file contains elements common to all pages; every other template will inherit from base.html. (parent template) -->

<!-- Load the collection of template tags available in bootstrap4. -->
{% load bootstrap4 %}

<!-- Declares the document as an HTML file. -->
<!doctype html>
<html lang="en">
    <!-- The head of an HTML file tells the browser what it needs to know to display the page correctly. -->
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">

        <!-- Displays the browser's title bar whenever Pizzeria is open. -->
        <title>Pizzeria</title>
        
        <!-- One of bootstrap's template tags, which tells django to include all bootstrap style files. -->
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}

    </head>
    <!-- Opens the body tag. -->
    <body>
        <!-- Indicates the page's navigation links section. 
            Everything contained in this element is styled according to the bootstrap style rules defined by the navbar selectors. -->
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <!-- Sets the project's name to appear at the far left of the navigation bar and make it a link to the home page.
            This appears on every page of the project. The navbar-brand selector styles this link to stand out from the rest of the links. -->
            <a class="navbar-brand" href="{% url 'pizzas:index' %}">
                Pizzeria</a>
            <!-- Defines a button that appears if the browser window is too narrow to display the whole navigation bar horizontally.
            When the user clicks the button, the navigation elements will appear in a drop-down list. The collapse reference causes 
            the navigation bar to collapse when the user shrinks the browser window or when the site is displayed on smaller screens. -->
            <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
            <!-- Opens a new section of the nav bar. Builds a web page by dividing it into sections and defining style and behavior rules that apply to that section. 
            The div function builds a web page by dividing it into sections and defining style and behavior rules that apply in the section. -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <!-- Define a new set of links. Bootstrap defines navigation elements as items in an unordered list with style rules. Every link or element
                you need on the bar can be included as an item in one of these lists. -->
                <ul class="navbar-nav mr-auto">
                    <!-- The only item in the list is our link to the Pizzas page. -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pizzas:pizzas' %}">
                            Pizzas</a></li>
                </ul>
            </div>
        </nav>
        <!-- Used for the most significant part of the body of a page. The container selector is a simple way to group elements on a page. -->
        <main role="main" class="container">
            <!-- This block will be used to title most pages and provide padding below the header. Padding refers to the sapce between 
            an element's content and its border, the border-bottom selector provides a thin border at the bottom of page_header block. -->
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %} {% endblock page_header %}
            </div>
            <!-- This div element contains the block content. Doesn't add a specific style to this block, which allows for styling the content
            of any page as we see fit for that page. -->
            <div>
                {% block content %} {% endblock content %}
            </div>
        </main>
    </body>
</html>

pizzas/templates/pizzas/comment.html
<!-- The beginning of the child template must have an extends tag to tell django which parent template to inheriate from. -->
{% extends "pizzas/base.html" %}

<!-- Everything that we aren't inheriting from the parent template will go inside the content block. -->
{% block content %}

<!-- Shows the pizza at the top of the page, so the user can see which pizza they're commenting on. -->
<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p>Add a comment:</p>
<!-- The form's action argument includes the pizza_id value in the url, so the view function can associate the comment with the correct pizza. -->
<form action="{% url 'pizzas:comment' pizza.id %}" method='post'>
    <!-- The crf tag prevents attackers from using the form to gain unauthorized access to the server. -->
    {% csrf_token %}
    <!-- This is the tag that displays the comment form. This includes the template variable for django to create the necessary fields to automatically display the form. -->
    <!-- The as_p modifier tells django to render all the form elements in paragraph format. -->
    {{ form.as_p }}
    <button name='submit'>Add comment</button>
</form>

{% endblock content %}
<!-- This indicates the we're finished defining the content in the block. -->

<!-- Once you have created the template in the fourth phase, you will need to link the html page on another page you desire. -->

pizzas/templates/pizzas/index.html
<!-- Allows the user to see this built html page instead of the default django page.
From the path function in the urls.py file in the pizzas app, Django will take the requested url and that url will match the pattern '',
then django will call the function views.index() to render the page using the template below. -->

<!-- The beginning of the child template must have an extends tag to tell django which parent template to inheriate from. -->
{% extends "pizzas/base.html" %}

<!-- Everything that we aren't inheriting from the parent template will go inside the content block. -->
{% block page_header %}

<div class="jumbotron">
    <h1 class="display-3">Welcome to the Pizzeria!</h1>

    <p class="lead">Take a look at what pizzas we have to offer, and the toppings that each pizza contains.</p>
</div>

{% endblock page_header %}
<!-- This indicates the we're finished defining the content in the block. -->

pizzas/templates/pizzas/pizza.html
<!-- The beginning of the child template must have an extends tag to tell django which parent template to inheriate from. -->
{% extends "pizzas/base.html" %}

{% block page_header %}
<h3>{{ pizza }}</h3>
{% endblock page_header %}

<!-- Everything that we aren't inheriting from the parent template will go inside the content block. -->
{% block content %}

<!-- Show the pizza that is currently being displayed. -->
<p>Pizza: {{ pizza }}</p>

<p>Toppings:</p>
<!-- Start of bulleted list to show each of the toppings. -->

{% for topping in toppings %}
<!-- Div element with the selector card. This card has one nested element to hold the body of the toppings and the comments. -->
<div class="card mb-3">
<!-- Places the text of the toppings and comments in a simple box on the card. -->
<div class="card-body">
    <!-- The linebreaks filter ensures that long text entries include line breaks in a format understood by browsers,
        instead of showing a block of uninterrupted text. -->
    {{ topping.text|linebreaks}}
</div>
</div>
        
{% empty %}
    <p>There are no toppings for this pizza yet.</p>
{% endfor %}

<!-- Include a link to the comment page from each pizza page. -->
<p>
    <a href="{% url 'pizzas:comment' pizza.id %}">Add comment</a>
</p>


{% endblock content %}
<!-- This indicates the we're finished defining the content in the block. -->

pizzas/templates/pizzas/pizzas.html
<!-- The beginning of the child template must have an extends tag to tell django which parent template to inheriate from. -->
{% extends "pizzas/base.html" %}

<!-- Move the heading into the page_header and give it a header styling. -->
{% block page_header %}
<h1>Pizzas</h1>
{% endblock page_header %}

<!-- Everything that we aren't inheriting from the parent template will go inside the content block. -->
{% block content %}

<ul>
    <!-- This loops through the list pizzas from the context dictionary. -->
    {% for pizza in pizzas %}
    <!-- Provides a link from the pizza page. -->
    <!-- h3 is an element that styles each pizza to make them a little larger on the page.-->
    <li><h3>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    </h3></li>
    <!-- This code for pizza will be replaced by the value of pizza on each pass through the loop. -->
    <!-- This tells django what to do if there are no items in the list. -->
    {% empty %}
    <li><h3>No pizzas have been added yet.</h3></li>
    <!-- This closes the for loop. -->
    {% endfor %}
</ul>

{% endblock content %}
<!-- This indicates the we're finished defining the content in the block. -->